<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
    'menu.startpage' => 'Startseite',
    'menu.account' => 'Kundenaccounts',
    'menu.user' => 'Nutzer',
    'menu.paymeyaccount' => 'PAYMEY-Konten',
    'menu.paymeyaccount.1' => 'Nicht aktivierte Konten anzeigen',
    'menu.transaction' => 'Transaktionen',
    'menu.transaction.1' => 'Offene Transaktionen anzeigen',
    'menu.transaction.-2' => 'Abgebrochene Transaktionen anzeigen',
    'menu.transaction.2' => 'Abgeschlossene Transaktionen anzeigen',
    'menu.logout' => 'Abmelden',

    'updateSuccess' => 'Ihre Änderungen wurden gespeichert!',
    'updateError' => 'Es ist leider ein Fehler aufgetreten!',

    'deleteSuccess' => 'Eintrag erfolgreich gelöscht!',
    'deleteError' => 'Beim löschen ist ein Fehler aufgetreten!',

    'activateUser' => 'Nutzer aktivieren',
    'blockUser' => 'Nutzer sperren',
);
